/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sofia
 */
import modelo.Calculator;
public class Calculadora extends javax.swing.JFrame 
{

    /**
     * Creates new form Calculadora
     */
    
    public Calculadora() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AC = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        DEL = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        substract = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        screenResult = new javax.swing.JLabel();
        screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(210, 352));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(210, 331));
        jPanel1.setMinimumSize(new java.awt.Dimension(210, 331));

        AC.setBackground(new java.awt.Color(255, 255, 255));
        AC.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        AC.setForeground(new java.awt.Color(51, 51, 51));
        AC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        AC.setText("AC");
        AC.setBorder(null);
        AC.setBorderPainted(false);
        AC.setContentAreaFilled(false);
        AC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AC.setOpaque(false);
        AC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        AC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1Mouse.png"))); // NOI18N
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        pi.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        pi.setForeground(new java.awt.Color(51, 51, 51));
        pi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        pi.setText("π");
        pi.setBorder(null);
        pi.setBorderPainted(false);
        pi.setContentAreaFilled(false);
        pi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        pi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1Mouse.png"))); // NOI18N
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });

        multiply.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        multiply.setForeground(new java.awt.Color(51, 51, 51));
        multiply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        multiply.setText("*");
        multiply.setBorder(null);
        multiply.setBorderPainted(false);
        multiply.setContentAreaFilled(false);
        multiply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiply.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        multiply.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1Mouse.png"))); // NOI18N
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        divide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        divide.setForeground(new java.awt.Color(51, 51, 51));
        divide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        divide.setText("/");
        divide.setBorder(null);
        divide.setBorderPainted(false);
        divide.setContentAreaFilled(false);
        divide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divide.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        divide.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1Mouse.png"))); // NOI18N
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        seven.setForeground(new java.awt.Color(51, 51, 51));
        seven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        seven.setText("7");
        seven.setBorderPainted(false);
        seven.setContentAreaFilled(false);
        seven.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seven.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        seven.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eight.setForeground(new java.awt.Color(51, 51, 51));
        eight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        eight.setText("8");
        eight.setBorderPainted(false);
        eight.setContentAreaFilled(false);
        eight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eight.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        eight.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nine.setForeground(new java.awt.Color(51, 51, 51));
        nine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        nine.setText("9");
        nine.setBorderPainted(false);
        nine.setContentAreaFilled(false);
        nine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nine.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        nine.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        four.setForeground(new java.awt.Color(51, 51, 51));
        four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        four.setText("4");
        four.setBorderPainted(false);
        four.setContentAreaFilled(false);
        four.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        four.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        four.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        five.setForeground(new java.awt.Color(51, 51, 51));
        five.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        five.setText("5");
        five.setBorderPainted(false);
        five.setContentAreaFilled(false);
        five.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        five.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        five.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        six.setForeground(new java.awt.Color(51, 51, 51));
        six.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        six.setText("6");
        six.setBorderPainted(false);
        six.setContentAreaFilled(false);
        six.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        six.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        six.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        one.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        one.setForeground(new java.awt.Color(51, 51, 51));
        one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        one.setText("1");
        one.setBorderPainted(false);
        one.setContentAreaFilled(false);
        one.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        one.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        one.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        two.setForeground(new java.awt.Color(51, 51, 51));
        two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        two.setText("2");
        two.setBorderPainted(false);
        two.setContentAreaFilled(false);
        two.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        two.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        two.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        three.setForeground(new java.awt.Color(51, 51, 51));
        three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        three.setText("3");
        three.setBorderPainted(false);
        three.setContentAreaFilled(false);
        three.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        three.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        three.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        cero.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cero.setForeground(new java.awt.Color(51, 51, 51));
        cero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        cero.setText("0");
        cero.setBorderPainted(false);
        cero.setContentAreaFilled(false);
        cero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        cero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        dot.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        dot.setForeground(new java.awt.Color(51, 51, 51));
        dot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        dot.setText(".");
        dot.setBorderPainted(false);
        dot.setContentAreaFilled(false);
        dot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dot.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        dot.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        DEL.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        DEL.setForeground(new java.awt.Color(51, 51, 51));
        DEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        DEL.setText("del");
        DEL.setBorderPainted(false);
        DEL.setContentAreaFilled(false);
        DEL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DEL.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3.png"))); // NOI18N
        DEL.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton3Mouse.png"))); // NOI18N
        DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELActionPerformed(evt);
            }
        });

        equal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        equal.setForeground(new java.awt.Color(51, 51, 51));
        equal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton2.png"))); // NOI18N
        equal.setText("=");
        equal.setBorder(null);
        equal.setBorderPainted(false);
        equal.setContentAreaFilled(false);
        equal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        equal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton2.png"))); // NOI18N
        equal.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton2Mouse.png"))); // NOI18N
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        substract.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        substract.setForeground(new java.awt.Color(51, 51, 51));
        substract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        substract.setText("-");
        substract.setBorder(null);
        substract.setBorderPainted(false);
        substract.setContentAreaFilled(false);
        substract.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        substract.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        substract.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1Mouse.png"))); // NOI18N
        substract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(51, 51, 51));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        add.setText("+");
        add.setBorder(null);
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1.png"))); // NOI18N
        add.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton1Mouse.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(substract, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substract, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DEL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(221, 245, 245));

        screenResult.setBackground(new java.awt.Color(255, 255, 255));
        screenResult.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        screenResult.setForeground(new java.awt.Color(102, 102, 102));
        screenResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        screen.setBackground(new java.awt.Color(255, 255, 255));
        screen.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        screen.setForeground(new java.awt.Color(51, 51, 51));
        screen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(screenResult, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screenResult, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screen, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        //si presione el igual guardo lo que este en la pantalla de abajo en la variable auxiliar num2
        num2 = this.screen.getText();

        //si lo que estaba en pantalla no es ninguna operacion
        if((!num2.equalsIgnoreCase("+")&&(!num2.equalsIgnoreCase("-")))&&
            (!num2.equalsIgnoreCase("*"))&&(!num2.equalsIgnoreCase("/")))
        {
            calculadora.setNum2(num2);//seteo el numero 2
        }

        //agrego a la pantalla de arriba el numero 2 y un igual
        this.screenResult.setText(this.screenResult.getText() + num2 + " = ");

        num2 = calculadora.calculate();//almaceno en num2 el resultado
        this.screen.setText(num2);//borro lo anterior de la pantalla de abajo y muestro el resultado

        deleteOperationScreen = true; //levanto la bandera de borrar la operacion en pantalla
        operation = ' '; //reinicio la variable que almacena la operacion en espacio

        if(calculadora.getError()) //verifico que el calculo no fue un error
        {
            //si hay un error
            calculadora.resetAtributs(); //reseteo los atributos de la calculadora
            num1 = "";//reseteo el numero 1
        }
        else
        num1 = num2; //si no hay error almaceno en num 1 el resultado
        num2 = ""; //num2 siempre se resetea
        pressEqual = true;//guardo que se presiono la tecla igual
        //esto me sirve en dos ocasiones :
        //         -al agregar un numero luego del calculo se reinicia todo
        //         -al realizar una operacion sobre el resultado
        numberPi=false;//si pi se agrego como num2 verifico que este booleano pase a false
    }//GEN-LAST:event_equalActionPerformed

    private void DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELActionPerformed
        // TODO add your handling code here:
        String aux = this.screen.getText();//guardo lo que esta actualmente en pantalla en un String auxiliar

        //borro el ultimo elemento del String y lo muestro en la pantalla
        //esto solo afecta a la pantalla de abajo, la que muestra los numeros que se estan agregando
        this.screen.setText(aux.replaceFirst(".$",""));
    }//GEN-LAST:event_DELActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        addNumber('7'); //agrega el numero 1 que se presiono con el boton '7'
    }//GEN-LAST:event_sevenActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        addNumber('5'); //agrega el numero 1 que se presiono con el boton '5'
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        addNumber('6'); //agrega el numero 1 que se presiono con el boton '6'
    }//GEN-LAST:event_sixActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        addNumber('1'); //agrega el numero 1 que se presiono con el boton '1'
    }//GEN-LAST:event_oneActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // TODO add your handling code here:
        //impido que agregen mas de un punto en pantalla, ya que los numeros
        //pueden tener solo una coma para decimales
        if(!this.screen.getText().contains(".")) //si el String en pantalla no tiene un punto lo agrego
        this.screen.setText(this.screen.getText()+".");
    }//GEN-LAST:event_dotActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        addNumber('9'); //agrega el numero 1 que se presiono con el boton '9'
    }//GEN-LAST:event_nineActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        operation = '/'; //guardo la operacion '/'

        addOperation(); //agrego la operacion
    }//GEN-LAST:event_divideActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        addNumber('3'); //agrega el numero 1 que se presiono con el boton '3'
    }//GEN-LAST:event_threeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        operation = '+'; //guardo la operacion '+'

        addOperation(); //agrego la operacion
    }//GEN-LAST:event_addActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        addNumber('4'); //agrega el numero 1 que se presiono con el boton '4'
    }//GEN-LAST:event_fourActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        // TODO add your handling code here:
        addNumber('0'); //agrega el numero 1 que se presiono con el boton '0'
    }//GEN-LAST:event_ceroActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        addNumber('8'); //agrega el numero 1 que se presiono con el boton '8'
    }//GEN-LAST:event_eightActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        operation = '*'; //guardo la operacion '*'

        addOperation(); //agrego la operacion
    }//GEN-LAST:event_multiplyActionPerformed

    private void substractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractActionPerformed
        // TODO add your handling code here:
        operation = '-'; //guardo la operacion '-'

        addOperation(); //agrego la operacion
    }//GEN-LAST:event_substractActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        // TODO add your handling code here:
        //al agregar PI no se puden agregar numeros adelante o atras de PI
        if(deleteOperationScreen)//si hay una operacion en la pantalla de abajo
        //si hay una operacion lo agrego a la pantalla de arriba
        this.screenResult.setText(this.screenResult.getText() + " " + operation);

        if(pressEqual)//si agrego PI luego de un resultado de operacion
        {
            calculadora.resetAtributs();//reseteo la calculadora
            this.screenResult.setText("");//borro la pantalla de resultados
            resetValues();//reseteo los valores temporales
        }

        //sin importar si la pantalla de abajo tiene numeros borro todo y agrego PI
        this.screen.setText(""+Math.PI);
        numberPi=true;
    }//GEN-LAST:event_piActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        addNumber('2'); //agrega el numero 1 que se presiono con el boton '2'
    }//GEN-LAST:event_twoActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        this.screen.setText(""); //borro todo en la pantalla de abajo
        this.screenResult.setText(""); //borro todo en la pantalla de arriba
        calculadora.resetAtributs(); //reseteo la calculadora
        resetValues(); //reseteo los valores temporales
    }//GEN-LAST:event_ACActionPerformed
    
    private void addOperation()
    {
        //si la auxiliar de num1 esta vacia o se presiono la tecla igual
        if((num1.isEmpty())||(pressEqual))
        {
            num1 = this.screen.getText();//asigno lo que este en pantalla a num1
            calculadora.setNum1(num1);//seteo num1 en la calculadora
            pressEqual = false;//reinicio el booleano de presionar igual
        }
        else
        {
            num2 = this.screen.getText();//guardo en num2 lo que este en pantalla
            calculadora.setNum2(num2);//seteo num2 en la calculadora
            num1 = calculadora.calculate();//guardo el calculo en num1 con los valores que existen
                                           //por si hay otro calculo
            num2 = "";//reinicio num2
        }
        
        if(!calculadora.getError()) //si no hay error
        {
            this.screenResult.setText(num1+" "); //reinicio la pantalla de arriba mostrando num1
            this.screen.setText(""+operation); //reinicio la pantalla de abajo mostrando la operacion
            calculadora.setOperation(operation);//seteo la operacion en la calculadora
        }
        else
        {
            this.screenResult.setText("");//si hay un error reinicio la pantalla de arriba
            this.screen.setText(num1);//reinicio la pantalla de abajo con el mensaje de error
            calculadora.resetAtributs();//reseteo los valores de la calculadora
            resetValues();//reseteo los valores temporales
        }
        
        numberPi=false;//por si PI estaba presionado lo paso a falso
        deleteOperationScreen = true;//paso como verdadero el borrar la pantalla de abajo
    }
    
    private void resetValues()
    {
        //reseteo los valores temporales
        num1 = "";
        num2 = "";
        operation = ' ';
    }
    
    private void addNumber(char number)
    {
        //si axiste el numero PI o se presiono una operacion antes (un calculo o un igual)
        if((numberPi)||(deleteOperationScreen)) 
        {
            //si hay una operacion sumo la operacion en la pantalla de arriba
            if((deleteOperationScreen))
                this.screenResult.setText(this.screenResult.getText() + operation + " ");
            
            //seteo en la pantalla de abajo el numero
            this.screen.setText(""+number);
            numberPi = false;//paso PI a falso
            deleteOperationScreen = false;//paso el eliminar pantalla por operacion a falso
        }
        else
            this.screen.setText(this.screen.getText()+number);//sino lo sumo a lo que hay en pantalla abajo
        
        //si se presiono igual y la operacion esta en vacio
        if(pressEqual && (operation == ' '))
        {
            this.screenResult.setText("");//reseteo la pantalla de arriba
            pressEqual = false;//paso el equal a false
        }
        
    }
    
    //--------------------------------------------------------------------------------------------------------------
    //redondear resultados a 5 numeros despues de la coma en pantalla
    //hacer un try catch en la division y tirar el error de no se puede dividir
    
    
    /**
     * @param args the command line arguments
     */
    //clase calculadora para realizar los calculos
    public static Calculator calculadora;
    
    //strings temporales de num1 y num2
    public static String num1, num2;
    
    //caracter temporal de la operacion
    public static char operation;
    
    //booleanos para saber si se apreto una tecla de operacion o la tecla igual
    public static boolean deleteOperationScreen, pressEqual;
    
    //booleano para saber si el numero pi se apreto, porque si pi esta
    //en la pantalla no tendria que poder agregarle numeros a pi
    public static boolean numberPi;
    public static void main(String args[]) 
    {
        calculadora = new Calculator();//inicializo la calculadora
        num1 = "";//numero 1 se inicializa vacio
        num2 = "";//numero 2 se inicializa vacio
        operation = ' ';//la operacion se inicializa con un espacio
        numberPi = false;//la tecla pi no esta precionada al inicio
        deleteOperationScreen = false;//al inicio no hay ninguna operacion a borrar en pantalla
        pressEqual = false;//al inicio no esta presionada la tecla igual
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton DEL;
    private javax.swing.JButton add;
    private javax.swing.JButton cero;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton pi;
    private javax.swing.JLabel screen;
    private javax.swing.JLabel screenResult;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton substract;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
